"""
TLT/SPY Color Day Trading Strategy — V5 (Magnitude-Weighted Hold & Add)

This module implements the complete trading strategy as described in STRATEGY.md.
It is designed to be imported by a trading agent that provides daily market data
and receives position-sizing instructions in return.

Usage:
    from strategy import ColorStrategy

    strategy = ColorStrategy(initial_capital=10000.0)

    # Each trading day, call evaluate() with today's data:
    action = strategy.evaluate(
        date="2024-01-15",
        spy_open=475.20,
        spy_close=472.85,
        spy_volume=98000000,
        tlt_close=92.40
    )

    # action is a dict:
    # {
    #     "target_exposure": 1.5,        # desired total exposure (1.0 = base, 2.0 = max)
    #     "color": "Blue",               # today's color
    #     "is_strong": True,             # SPY moved > 1%
    #     "signal": "T1_BOTH_STRONG_BLUE",  # active signal name or ""
    #     "tier": 1,                     # signal tier (0 = none, 1-3)
    #     "boost_action": "OPEN",        # "OPEN", "HOLD", "CLOSE", "NONE"
    #     "boost_hold_days": 3,          # days remaining on boost
    #     "danger": False,               # True if danger signal fired
    #     "greed_trim": False,           # True if greed triggered trim
    #     "reason": "Both-Strong Blue: SPY -1.5%, TLT +1.2%"  # human-readable
    # }

Author: Generated by Claude for TLT/SPY Color Strategy project
Version: 5.0
"""

import math

import numpy as np
from collections import deque
from datetime import datetime, timedelta
from typing import Optional, TypedDict


class EvaluateResult(TypedDict):
    target_exposure: float
    color: str
    is_strong: bool
    signal: str
    tier: int
    boost_action: str
    boost_hold_days: int
    danger: bool
    greed_trim: bool
    reason: str


class ColorStrategy:
    """
    Magnitude-weighted Hold & Add strategy using TLT/SPY color classification.

    The strategy maintains a permanent 1x long SPY position and tactically
    adds leverage (up to 2x) on high-conviction color day signals.

    No stop losses. Boosts are time-limited or streak-based.
    """

    # ------------------------------------------------------------------ #
    #  Configuration constants                                            #
    # ------------------------------------------------------------------ #

    # Magnitude threshold: SPY daily move > this % counts as "strong"
    STRONG_THRESHOLD_PCT = 1.0

    # Correlation lookback (trading days)
    CORRELATION_LOOKBACK = 20

    # Moving average lookbacks
    SMA_50_LOOKBACK = 50
    SMA_200_LOOKBACK = 200

    # Volume ratio lookback
    VOLUME_LOOKBACK = 20

    # Greed score threshold (5-day cumulative up-move magnitude)
    GREED_THRESHOLD = 6.0
    GREED_LOOKBACK = 5

    # Fear score lookback
    FEAR_LOOKBACK = 3

    # Danger: consecutive Blue days that trigger full exit
    # Bull regime (SPY >= 200d SMA): 4 consecutive Blue days → 2-day sit-out
    # Bear regime (SPY < 200d SMA): tighter — 3 consecutive Blue days → 3-day sit-out
    DANGER_BLUE_STREAK = 4
    DANGER_SIT_OUT_DAYS = 2
    DANGER_BLUE_STREAK_BEAR = 3   # regime-adaptive trigger
    DANGER_SIT_OUT_DAYS_BEAR = 3  # regime-adaptive sit-out

    # ------------------------------------------------------------------ #
    #  Signal definitions                                                 #
    # ------------------------------------------------------------------ #
    #
    #  Each signal is a dict with:
    #    name: str           — unique identifier
    #    tier: int           — 1 (max), 2 (high), 3 (moderate)
    #    boost_mult: float   — extra exposure on top of 1x base
    #    hold_days: int      — how many days to hold (0 = streak-based)
    #    streak_color: str   — if set, exit when this color streak breaks
    #
    #  Signals are evaluated in priority order (first match wins).
    # ------------------------------------------------------------------ #

    SIGNALS = [
        # --- TIER 1: 2x total ---
        {
            "name": "T1_BOTH_STRONG_BLUE",
            "tier": 1,
            "boost_mult": 1.0,
            "hold_days": 3,
            "streak_color": None,
        },
        {
            "name": "T1_STRONG_HIVOL_RED",
            "tier": 1,
            "boost_mult": 1.0,
            "hold_days": 3,
            "streak_color": None,
        },
        {
            "name": "T1_STRONG_RED_STREAK",
            "tier": 1,
            "boost_mult": 1.0,
            "hold_days": 1,
            "streak_color": None,
        },
        # --- TIER 2: 1.5x total ---
        {
            "name": "T2_STRONG_BLUE_NEGCORR",
            "tier": 2,
            "boost_mult": 0.5,
            "hold_days": 3,
            "streak_color": None,
        },
        {
            "name": "T2_WEAK_RED_EXHAUSTION",
            "tier": 2,
            "boost_mult": 0.5,
            "hold_days": 1,
            "streak_color": None,
        },
        {
            "name": "T2_GREEN_MOMENTUM",
            "tier": 2,
            "boost_mult": 0.5,   # overridden to 1.0 if trend_bull
            "hold_days": 15,
            "streak_color": "Green",
        },
        {
            "name": "T2_SPY_DOWN_STREAK",
            "tier": 2,
            "boost_mult": 0.5,
            "hold_days": 1,
            "streak_color": None,
        },
        # --- TIER 3: 1.25x total ---
        {
            "name": "T3_WEAK_BLUE_NEGCORR",
            "tier": 3,
            "boost_mult": 0.25,
            "hold_days": 3,
            "streak_color": None,
        },
        {
            "name": "T3_ORANGE_GRIND",
            "tier": 3,
            "boost_mult": 0.25,
            "hold_days": 10,
            "streak_color": "Orange",
        },
    ]

    # ------------------------------------------------------------------ #
    #  Initialization                                                     #
    # ------------------------------------------------------------------ #

    def __init__(self, initial_capital: float = 10000.0, use_breadth: bool = True):
        self.initial_capital = initial_capital
        self.use_breadth = use_breadth

        # Price / return history (deques for rolling calculations)
        self.spy_closes = deque(maxlen=self.SMA_200_LOOKBACK + 1)
        self.spy_opens = deque(maxlen=5)
        self.spy_volumes = deque(maxlen=self.VOLUME_LOOKBACK + 1)
        self.tlt_closes = deque(maxlen=self.CORRELATION_LOOKBACK + 1)
        self.spy_returns = deque(maxlen=self.CORRELATION_LOOKBACK + 1)
        self.tlt_returns = deque(maxlen=self.CORRELATION_LOOKBACK + 1)

        # Color history
        self.colors = deque(maxlen=20)
        self.is_strong_history = deque(maxlen=20)

        # Streak counters
        self.streaks = {"Red": 0, "Blue": 0, "Green": 0, "Orange": 0}
        self.red_strong_in_streak = 0
        self.spy_down_streak = 0

        # Fear / Greed score components
        self.fear_contribs = deque(maxlen=max(self.FEAR_LOOKBACK, self.GREED_LOOKBACK) + 1)
        self.greed_contribs = deque(maxlen=self.GREED_LOOKBACK + 1)

        # Boost state
        self.boost_active = False
        self.boost_signal_name = ""
        self.boost_tier = 0
        self.boost_mult = 0.0
        self.boost_days_remaining = 0
        self.boost_streak_color: Optional[str] = None
        self.boost_entry_price = 0.0

        # Danger state
        self.danger_active = False
        self.danger_days_remaining = 0

        # Suppression: after strong up day, skip next day for new boosts
        self.suppress_next_boost = False

        # RSP breadth tracking
        self.rsp_closes = deque(maxlen=21)
        self.rsp_returns = deque(maxlen=21)
        self.rsp_spy_ratios = deque(maxlen=21)   # rsp_ret - spy_ret per day
        self.prev_rsp_close: Optional[float] = None

        # Day counter
        self.day_count = 0
        self._last_date = None
        self.prev_spy_close: Optional[float] = None
        self.prev_tlt_close: Optional[float] = None

    # ------------------------------------------------------------------ #
    #  Core calculations                                                  #
    # ------------------------------------------------------------------ #

    def _classify_color(self, spy_chg: float, tlt_chg: float) -> str:
        spy_up = spy_chg > 0
        tlt_up = tlt_chg > 0
        if spy_up and tlt_up:
            return "Green"
        elif spy_up and not tlt_up:
            return "Orange"
        elif not spy_up and tlt_up:
            return "Blue"
        else:
            return "Red"

    def _rolling_correlation(self) -> float:
        if len(self.spy_returns) < self.CORRELATION_LOOKBACK:
            return 0.0
        spy = list(self.spy_returns)[-self.CORRELATION_LOOKBACK:]
        tlt = list(self.tlt_returns)[-self.CORRELATION_LOOKBACK:]
        if np.std(spy) == 0 or np.std(tlt) == 0:
            return 0.0
        return float(np.corrcoef(spy, tlt)[0, 1])

    def _sma(self, lookback: int) -> Optional[float]:
        if len(self.spy_closes) < lookback:
            return None
        return float(np.mean(list(self.spy_closes)[-lookback:]))

    def _volume_ratio(self) -> float:
        if len(self.spy_volumes) < self.VOLUME_LOOKBACK:
            return 1.0
        avg = np.mean(list(self.spy_volumes)[-self.VOLUME_LOOKBACK:])
        if avg == 0:
            return 1.0
        return float(list(self.spy_volumes)[-1] / avg)

    def _fear_score(self, lookback: int) -> float:
        contribs = list(self.fear_contribs)[-lookback:]
        return sum(contribs) if contribs else 0.0

    def _greed_score(self) -> float:
        contribs = list(self.greed_contribs)[-self.GREED_LOOKBACK:]
        return sum(contribs) if contribs else 0.0

    def _update_streaks(self, color: str, is_strong: bool):
        for c in self.streaks:
            if c == color:
                self.streaks[c] += 1
            else:
                self.streaks[c] = 0

        if color == "Red":
            if is_strong:
                self.red_strong_in_streak += 1
        else:
            self.red_strong_in_streak = 0

    def _update_spy_down_streak(self, spy_chg: float):
        if spy_chg < 0:
            self.spy_down_streak += 1
        else:
            self.spy_down_streak = 0

    # ------------------------------------------------------------------ #
    #  Signal detection                                                   #
    # ------------------------------------------------------------------ #

    def _detect_signal(
        self,
        color: str,
        is_strong: bool,
        both_strong: bool,
        corr: float,
        vol_ratio: float,
        trend_bull: bool,
    ) -> Optional[dict]:
        """
        Evaluate signals in priority order. Return the first match or None.
        """

        # T1: Both-Strong Blue
        if color == "Blue" and both_strong:
            return self.SIGNALS[0]  # T1_BOTH_STRONG_BLUE

        # T1: Strong Red + High Volume
        if color == "Red" and is_strong and vol_ratio > 1.5:
            return self.SIGNALS[1]  # T1_STRONG_HIVOL_RED

        # T1: Strong Red Streak (3+ Red, ≥2 strong in streak)
        if self.streaks["Red"] >= 3 and self.red_strong_in_streak >= 2:
            return self.SIGNALS[2]  # T1_STRONG_RED_STREAK

        # T2: Strong Blue + Negative Correlation
        if color == "Blue" and is_strong and corr < -0.3:
            return self.SIGNALS[3]  # T2_STRONG_BLUE_NEGCORR

        # T2: Weak Red Exhaustion (3+ Red, all weak)
        if self.streaks["Red"] >= 3 and self.red_strong_in_streak == 0:
            return self.SIGNALS[4]  # T2_WEAK_RED_EXHAUSTION

        # T2: Green Momentum (3+ streak, last day not strong)
        if self.streaks["Green"] >= 3 and not is_strong:
            sig = dict(self.SIGNALS[5])  # T2_GREEN_MOMENTUM (copy)
            if trend_bull:
                sig["boost_mult"] = 1.0  # 2x in bull trend
            return sig

        # T2: SPY Down Streak (4+ days)
        if self.spy_down_streak >= 4:
            return self.SIGNALS[6]  # T2_SPY_DOWN_STREAK

        # T3: Weak Blue + Negative Correlation
        if color == "Blue" and not is_strong and corr < -0.3:
            return self.SIGNALS[7]  # T3_WEAK_BLUE_NEGCORR

        # T3: Orange Grind (3+ streak)
        if self.streaks["Orange"] >= 3:
            return self.SIGNALS[8]  # T3_ORANGE_GRIND

        return None

    # ------------------------------------------------------------------ #
    #  RSP breadth helpers                                                #
    # ------------------------------------------------------------------ #

    def _breadth_5d(self) -> Optional[float]:
        """5-day rolling breadth score: sum of (RSP_ret - SPY_ret).
        Positive = broad market outperforming (healthy).
        Negative = narrow/mega-cap driven (fragile).
        Returns None if insufficient RSP data."""
        ratios = list(self.rsp_spy_ratios)
        if len(ratios) < 5:
            return None
        return sum(ratios[-5:]) * 100  # convert to percentage points

    def _streak_breadth(self, color: str) -> Optional[float]:
        """Breadth accumulated over the current streak of `color`.
        Returns None if insufficient RSP data."""
        streak_len = self.streaks.get(color, 0)
        ratios = list(self.rsp_spy_ratios)
        if streak_len == 0 or len(ratios) < streak_len:
            return None
        return sum(ratios[-streak_len:]) * 100

    def _apply_breadth_modifier(
        self,
        signal: dict,
        breadth_5d: Optional[float],
        streak_breadth: Optional[float],
    ) -> Optional[dict]:
        """Post-detection signal modifier based on RSP breadth.

        Adjusts sizing or hold duration of detected signals, or suppresses
        them entirely. Returns modified signal dict, or None to suppress.
        When breadth data is unavailable, returns signal unchanged.
        """
        if breadth_5d is None:
            return signal

        name = signal["name"]

        # T1_BOTH_STRONG_BLUE: extend hold when breadth confirms
        if name == "T1_BOTH_STRONG_BLUE" and breadth_5d > 0.5:
            sig = dict(signal)
            sig["hold_days"] = 4
            return sig

        # T1_STRONG_HIVOL_RED: extend hold when breadth confirms
        if name == "T1_STRONG_HIVOL_RED" and breadth_5d > 0.5:
            sig = dict(signal)
            sig["hold_days"] = 4
            return sig

        # T2_GREEN_MOMENTUM: upgrade to T1 sizing when broad-based
        if name == "T2_GREEN_MOMENTUM" and breadth_5d > 1.0:
            sig = dict(signal)
            sig["boost_mult"] = 1.0
            return sig

        # T2_SPY_DOWN_STREAK: upgrade when equal-weight holds up over the down streak
        if name == "T2_SPY_DOWN_STREAK":
            ratios = list(self.rsp_spy_ratios)
            if self.spy_down_streak > 0 and len(ratios) >= self.spy_down_streak:
                down_streak_breadth = sum(ratios[-self.spy_down_streak:]) * 100
                if down_streak_breadth > 1.0:
                    sig = dict(signal)
                    sig["boost_mult"] = 1.0
                    return sig
            return signal

        # T3_WEAK_BLUE_NEGCORR: upgrade to T2 sizing when breadth confirms
        if name == "T3_WEAK_BLUE_NEGCORR" and breadth_5d > 0.5:
            sig = dict(signal)
            sig["boost_mult"] = 0.5
            return sig

        # T3_ORANGE_GRIND: suppress on narrow rally
        if name == "T3_ORANGE_GRIND" and breadth_5d < -1.0:
            return None

        return signal

    # ------------------------------------------------------------------ #
    #  Main evaluation — call once per trading day at close                #
    # ------------------------------------------------------------------ #

    def evaluate(
        self,
        date: str,
        spy_open: float,
        spy_close: float,
        spy_volume: int,
        tlt_close: float,
        rsp_close: Optional[float] = None,
    ) -> EvaluateResult:
        """
        Evaluate the strategy for today. Call at market close with today's data.
        Returns a dict describing the desired position for the NEXT trading day.

        Parameters
        ----------
        date : str          — ISO date string (e.g. "2024-01-15")
        spy_open : float    — SPY opening price today
        spy_close : float   — SPY closing price today
        spy_volume : int    — SPY volume today
        tlt_close : float   — TLT closing price today
        rsp_close : float   — RSP closing price today (None before May 2003)

        Returns
        -------
        dict with keys:
            target_exposure (float):  desired total exposure for next open
                                      1.0 = base only, 2.0 = max leverage
            color (str):              today's color
            is_strong (bool):         whether today was a strong day
            signal (str):             active boost signal name, or ""
            tier (int):               signal tier (0-3)
            boost_action (str):       "OPEN", "HOLD", "CLOSE", "NONE"
            boost_hold_days (int):    days remaining on boost
            danger (bool):            whether danger signal is active
            greed_trim (bool):        whether greed triggered a trim
            reason (str):             human-readable explanation
        """

        self.day_count += 1

        # ── Input validation ──────────────────────────────────────────────────
        parsed_date = datetime.strptime(date, "%Y-%m-%d").date()
        if self._last_date is not None and parsed_date <= self._last_date:
            raise ValueError(f"Date {date} is not after previous date {self._last_date}")
        self._last_date = parsed_date

        for name, val in [("spy_open", spy_open), ("spy_close", spy_close), ("tlt_close", tlt_close)]:
            if not isinstance(val, (int, float)) or math.isnan(val) or math.isinf(val):
                raise ValueError(f"{name} must be a finite number, got {val}")
            if val <= 0:
                raise ValueError(f"{name} must be positive, got {val}")

        if spy_volume < 0:
            raise ValueError(f"spy_volume must be non-negative, got {spy_volume}")

        if rsp_close is not None:
            if not isinstance(rsp_close, (int, float)) or math.isnan(rsp_close) or math.isinf(rsp_close):
                raise ValueError(f"rsp_close must be a finite number, got {rsp_close}")
            if rsp_close <= 0:
                raise ValueError(f"rsp_close must be positive, got {rsp_close}")

        # Store prices
        self.spy_closes.append(spy_close)
        self.spy_opens.append(spy_open)
        self.spy_volumes.append(spy_volume)
        self.tlt_closes.append(tlt_close)

        # Compute daily returns
        if self.prev_spy_close is not None and self.prev_tlt_close is not None:
            spy_chg = (spy_close / self.prev_spy_close) - 1
            tlt_chg = (tlt_close / self.prev_tlt_close) - 1
        else:
            self.prev_spy_close = spy_close
            self.prev_tlt_close = tlt_close
            return self._make_result(
                1.0, "N/A", False, "", 0, "NONE", 0, False, False,
                "First day — establishing base position."
            )

        self.spy_returns.append(spy_chg)
        self.tlt_returns.append(tlt_chg)
        self.prev_spy_close = spy_close
        self.prev_tlt_close = tlt_close

        # RSP breadth (optional — None before May 2003)
        if rsp_close is not None:
            self.rsp_closes.append(rsp_close)
            if self.prev_rsp_close is not None:
                rsp_ret = (rsp_close / self.prev_rsp_close) - 1
                self.rsp_returns.append(rsp_ret)
                self.rsp_spy_ratios.append(rsp_ret - spy_chg)  # positive = broad strength
            self.prev_rsp_close = rsp_close

        # Classify today
        color = self._classify_color(spy_chg, tlt_chg)
        spy_abs_pct = abs(spy_chg) * 100
        tlt_abs_pct = abs(tlt_chg) * 100
        is_strong = spy_abs_pct > self.STRONG_THRESHOLD_PCT
        both_strong = is_strong and tlt_abs_pct > self.STRONG_THRESHOLD_PCT

        self.colors.append(color)
        self.is_strong_history.append(is_strong)
        self._update_streaks(color, is_strong)
        self._update_spy_down_streak(spy_chg)

        # Fear / Greed
        if color in ("Red", "Blue"):
            self.fear_contribs.append(spy_abs_pct)
            self.greed_contribs.append(0.0)
        elif color in ("Green", "Orange"):
            self.fear_contribs.append(0.0)
            self.greed_contribs.append(spy_abs_pct)
        else:
            self.fear_contribs.append(0.0)
            self.greed_contribs.append(0.0)

        # Technical indicators
        corr = self._rolling_correlation()
        vol_ratio = self._volume_ratio()
        sma50 = self._sma(self.SMA_50_LOOKBACK)
        sma200 = self._sma(self.SMA_200_LOOKBACK)
        trend_bull = (
            sma50 is not None
            and sma200 is not None
            and spy_close > sma50
            and spy_close > sma200
        )

        # Bear regime: SPY is below its 200-day SMA.
        # Triggers tighter danger thresholds (earlier exit, longer sit-out).
        bear_regime = sma200 is not None and spy_close < sma200

        greed_5d = self._greed_score()
        fear_3d = self._fear_score(self.FEAR_LOOKBACK)

        # ============================================================ #
        #  STEP 1: Handle danger state                                  #
        # ============================================================ #

        if self.danger_active:
            self.danger_days_remaining -= 1
            if self.danger_days_remaining <= 0:
                self.danger_active = False
                return self._make_result(
                    1.0, color, is_strong, "", 0, "NONE", 0, False, False,
                    "Danger period over. Re-entering base 1x position."
                )
            else:
                return self._make_result(
                    0.0, color, is_strong, "", 0, "NONE",
                    self.danger_days_remaining, True, False,
                    f"Danger active — flat for {self.danger_days_remaining} more day(s)."
                )

        # Check for NEW danger: consecutive Blue streak exceeds regime threshold.
        # Bear regime (SPY < 200d SMA) uses a tighter trigger and longer sit-out.
        eff_danger_streak = self.DANGER_BLUE_STREAK_BEAR if bear_regime else self.DANGER_BLUE_STREAK
        eff_sit_out = self.DANGER_SIT_OUT_DAYS_BEAR if bear_regime else self.DANGER_SIT_OUT_DAYS
        if self.streaks["Blue"] >= eff_danger_streak:
            self.danger_active = True
            self.danger_days_remaining = eff_sit_out
            self.boost_active = False
            self.boost_signal_name = ""
            regime_note = " (bear regime)" if bear_regime else ""
            return self._make_result(
                0.0, color, is_strong, "", 0, "CLOSE", 0, True, False,
                f"DANGER{regime_note}: {self.streaks['Blue']} consecutive Blue days. "
                f"Selling everything. Sitting out {eff_sit_out} days."
            )

        # ============================================================ #
        #  STEP 2: Manage existing boost                                #
        # ============================================================ #

        boost_action = "NONE"
        greed_trim = False

        if self.boost_active:
            # Check greed trim
            if greed_5d >= self.GREED_THRESHOLD:
                self.boost_active = False
                boost_action = "CLOSE"
                greed_trim = True
                reason = (
                    f"Greed trim: 5d greed score = {greed_5d:.1f} "
                    f"(threshold {self.GREED_THRESHOLD}). Closing boost."
                )
                old_signal = self.boost_signal_name
                old_tier = self.boost_tier
                self.boost_signal_name = ""
                self.boost_tier = 0
                self.suppress_next_boost = False
                return self._make_result(
                    1.0, color, is_strong, old_signal, old_tier,
                    boost_action, 0, False, greed_trim, reason
                )

            # Check streak break
            if (
                self.boost_streak_color is not None
                and color != self.boost_streak_color
            ):
                self.boost_active = False
                boost_action = "CLOSE"
                reason = (
                    f"Streak break: expected {self.boost_streak_color}, "
                    f"got {color}. Closing boost."
                )
                old_signal = self.boost_signal_name
                old_tier = self.boost_tier
                self.boost_signal_name = ""
                self.boost_tier = 0
                return self._make_result(
                    1.0, color, is_strong, old_signal, old_tier,
                    boost_action, 0, False, False, reason
                )

            # Check hold limit
            self.boost_days_remaining -= 1
            if self.boost_days_remaining <= 0:
                self.boost_active = False
                boost_action = "CLOSE"
                reason = f"Hold limit reached for {self.boost_signal_name}. Closing boost."
                old_signal = self.boost_signal_name
                old_tier = self.boost_tier
                self.boost_signal_name = ""
                self.boost_tier = 0
                return self._make_result(
                    1.0, color, is_strong, old_signal, old_tier,
                    boost_action, 0, False, False, reason
                )

            # Boost still active — hold
            return self._make_result(
                1.0 + self.boost_mult, color, is_strong,
                self.boost_signal_name, self.boost_tier, "HOLD",
                self.boost_days_remaining, False, False,
                f"Holding boost {self.boost_signal_name} — "
                f"{self.boost_days_remaining} day(s) remaining."
            )

        # ============================================================ #
        #  STEP 3: Check suppression                                    #
        # ============================================================ #

        if self.suppress_next_boost:
            self.suppress_next_boost = False
            # Set suppression for NEXT day if today was strong up
            if color in ("Green", "Orange") and is_strong:
                self.suppress_next_boost = True
            return self._make_result(
                1.0, color, is_strong, "", 0, "NONE", 0, False, False,
                "Suppressed: skipping boost after previous strong up day."
            )

        # Set suppression for tomorrow if today is strong up
        if color in ("Green", "Orange") and is_strong:
            self.suppress_next_boost = True

        # ============================================================ #
        #  STEP 4: Detect new signal                                    #
        # ============================================================ #

        if self.day_count <= self.SMA_200_LOOKBACK:
            return self._make_result(
                1.0, color, is_strong, "", 0, "NONE", 0, False, False,
                f"Warming up ({self.day_count}/{self.SMA_200_LOOKBACK} days). Base only."
            )

        signal = self._detect_signal(
            color, is_strong, both_strong, corr, vol_ratio, trend_bull
        )

        # Apply RSP breadth modifier (post-detection, pre-activation)
        if signal is not None and self.use_breadth:
            breadth_5d = self._breadth_5d()
            color_for_streak = signal.get("streak_color") or color
            streak_b = self._streak_breadth(color_for_streak)
            signal = self._apply_breadth_modifier(signal, breadth_5d, streak_b)

        if signal is not None:
            self.boost_active = True
            self.boost_signal_name = signal["name"]
            self.boost_tier = signal["tier"]
            self.boost_mult = signal["boost_mult"]
            self.boost_days_remaining = signal["hold_days"]
            self.boost_streak_color = signal.get("streak_color")

            target = 1.0 + signal["boost_mult"]
            target = min(target, 2.0)  # cap at 2x

            hold_desc = (
                f"{signal['hold_days']} day(s)"
                if signal.get("streak_color") is None
                else f"while {signal['streak_color']} streak continues"
            )

            return self._make_result(
                target, color, is_strong, signal["name"], signal["tier"],
                "OPEN", signal["hold_days"], False, False,
                f"Signal: {signal['name']} (Tier {signal['tier']}). "
                f"Boosting to {target:.2f}x for {hold_desc}. "
                f"[SPY {spy_chg*100:+.2f}%, TLT {tlt_chg*100:+.2f}%, "
                f"corr={corr:.2f}, vol_ratio={vol_ratio:.2f}]"
            )

        # No signal — hold base
        return self._make_result(
            1.0, color, is_strong, "", 0, "NONE", 0, False, False,
            f"No signal. Holding base 1x. "
            f"[{color}{' (Strong)' if is_strong else ''}, "
            f"corr={corr:.2f}, greed={greed_5d:.1f}]"
        )

    # ------------------------------------------------------------------ #
    #  Result builder                                                     #
    # ------------------------------------------------------------------ #

    def _make_result(
        self,
        target_exposure: float,
        color: str,
        is_strong: bool,
        signal: str,
        tier: int,
        boost_action: str,
        boost_hold_days: int,
        danger: bool,
        greed_trim: bool,
        reason: str,
    ) -> EvaluateResult:
        return {
            "target_exposure": round(target_exposure, 4),
            "color": color,
            "is_strong": is_strong,
            "signal": signal,
            "tier": tier,
            "boost_action": boost_action,
            "boost_hold_days": boost_hold_days,
            "danger": danger,
            "greed_trim": greed_trim,
            "reason": reason,
        }

    # ------------------------------------------------------------------ #
    #  State inspection (for logging / debugging)                         #
    # ------------------------------------------------------------------ #

    def get_state(self) -> dict:
        """Return a snapshot of the strategy's internal state."""
        sma200 = self._sma(self.SMA_200_LOOKBACK)
        spy_close = list(self.spy_closes)[-1] if self.spy_closes else None
        bear_regime = sma200 is not None and spy_close is not None and spy_close < sma200
        return {
            "day_count": self.day_count,
            "streaks": dict(self.streaks),
            "spy_down_streak": self.spy_down_streak,
            "red_strong_in_streak": self.red_strong_in_streak,
            "boost_active": self.boost_active,
            "boost_signal": self.boost_signal_name,
            "boost_tier": self.boost_tier,
            "boost_mult": self.boost_mult,
            "boost_days_remaining": self.boost_days_remaining,
            "danger_active": self.danger_active,
            "danger_days_remaining": self.danger_days_remaining,
            "suppress_next_boost": self.suppress_next_boost,
            "correlation_20d": self._rolling_correlation(),
            "greed_5d": self._greed_score(),
            "fear_3d": self._fear_score(self.FEAR_LOOKBACK),
            "sma_50": self._sma(self.SMA_50_LOOKBACK),
            "sma_200": sma200,
            "bear_regime": bear_regime,
            "breadth_5d": self._breadth_5d(),
        }
