#!/usr/bin/env bash
# bootstrap.sh — One-shot setup for the AI Investing (Zo-professional) course.
#
# Idempotent. Safe to re-run. Each step prints what it's doing and either
# performs the action or skips it because the desired state already exists.
#
# Steps:
#   1. Locate the course repo
#   2. Install uv if missing
#   3. uv sync both course MCP servers
#   4. Generate MCP launcher scripts (absolute-path wrappers for supervisord)
#   5. Install Ollama if missing
#   6. Ensure ollama daemon is running
#   7. Pull gemma4:e2b
#   8. Patch page-index-rag-course/config.json to use gemma4:e2b
#   9. Install consumer skills into /home/workspace/Skills/
#  10. Run verify.sh

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Pretty output
# ─────────────────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

step()  { printf "\n${BOLD}▸ %s${RESET}\n" "$*"; }
ok()    { printf "  ${GREEN}✓${RESET} %s\n" "$*"; }
skip()  { printf "  ${DIM}↷ %s${RESET}\n" "$*"; }
warn()  { printf "  ${YELLOW}⚠ %s${RESET}\n" "$*"; }
fail()  { printf "  ${RED}✗ %s${RESET}\n" "$*"; exit 1; }

# ─────────────────────────────────────────────────────────────────────────────
# 1. Locate the course repo
# ─────────────────────────────────────────────────────────────────────────────
step "Locating course repo"

if [[ -n "${ZO_COURSE_REPO:-}" ]] && [[ -d "$ZO_COURSE_REPO" ]]; then
  REPO="$ZO_COURSE_REPO"
elif [[ -d "/home/workspace/AI-Investing-Course/repo" ]]; then
  REPO="/home/workspace/AI-Investing-Course/repo"
elif [[ -d "/home/workspace/ai-investment-courses" ]]; then
  REPO="/home/workspace/ai-investment-courses"
else
  fail "Course repo not found. Set ZO_COURSE_REPO or clone https://github.com/jingerzz/ai-investment-courses to /home/workspace/ai-investment-courses"
fi

SPY_TLT_DIR="$REPO/professional/servers/spy-tlt-course"
RAG_DIR="$REPO/professional/servers/page-index-rag-course"
SKILLS_SRC="$REPO/zo-professional/skills"
SKILLS_DST="${ZO_SKILLS_DIR:-/home/workspace/Skills}"

[[ -d "$SPY_TLT_DIR" ]] || fail "Missing $SPY_TLT_DIR"
[[ -d "$RAG_DIR" ]]     || fail "Missing $RAG_DIR"
[[ -d "$SKILLS_SRC" ]]  || fail "Missing $SKILLS_SRC"

ok "Repo: $REPO"

# ─────────────────────────────────────────────────────────────────────────────
# 2. Install uv if missing
# ─────────────────────────────────────────────────────────────────────────────
step "Checking uv"

if command -v uv >/dev/null 2>&1; then
  skip "uv already installed ($(uv --version))"
else
  warn "uv not found — installing from astral.sh"
  curl -LsSf https://astral.sh/uv/install.sh | sh
  # Make uv available in this shell
  export PATH="$HOME/.local/bin:$PATH"
  command -v uv >/dev/null 2>&1 || fail "uv install failed — see https://docs.astral.sh/uv/getting-started/installation/"
  ok "uv installed ($(uv --version))"
fi

# ─────────────────────────────────────────────────────────────────────────────
# 3. uv sync both servers
# ─────────────────────────────────────────────────────────────────────────────
step "Syncing spy-tlt-course"
( cd "$SPY_TLT_DIR" && uv sync --quiet )
ok "spy-tlt-course dependencies installed"

step "Syncing page-index-rag-course"
( cd "$RAG_DIR" && uv sync --quiet )
ok "page-index-rag-course dependencies installed"

# ─────────────────────────────────────────────────────────────────────────────
# 4. Generate MCP launcher scripts
#
# Why this exists: Zo registers user MCP servers via supervisord-user, which
# uses exec-style spawning. Commands like `cd <dir> && uv run xxx` silently
# fail because supervisord tries to exec the literal `cd` binary. Solution:
# write small wrapper scripts that handle the cd + absolute uv path
# internally, and register THOSE as the supervisord command.
# ─────────────────────────────────────────────────────────────────────────────
step "Generating MCP launcher scripts"

UV_BIN="$(command -v uv)"
[[ -n "$UV_BIN" ]] || fail "uv not found on PATH after install — cannot resolve absolute path for launchers"

LAUNCHER_DIR="$(dirname "$0")"
SPY_TLT_LAUNCHER="$LAUNCHER_DIR/run-spy-tlt-server.sh"
RAG_LAUNCHER="$LAUNCHER_DIR/run-rag-server.sh"

cat > "$SPY_TLT_LAUNCHER" <<LAUNCHER_EOF
#!/usr/bin/env bash
# Auto-generated by bootstrap.sh — do not commit; do not hand-edit.
# supervisord-user command for the spy-tlt-course MCP service.
# Re-run bootstrap.sh to regenerate after a path change.
set -euo pipefail
cd "$SPY_TLT_DIR"
exec "$UV_BIN" run spy-tlt-server
LAUNCHER_EOF

cat > "$RAG_LAUNCHER" <<LAUNCHER_EOF
#!/usr/bin/env bash
# Auto-generated by bootstrap.sh — do not commit; do not hand-edit.
# supervisord-user command for the page-index-rag-course MCP service.
# Re-run bootstrap.sh to regenerate after a path change.
set -euo pipefail
cd "$RAG_DIR"
exec "$UV_BIN" run rag-server
LAUNCHER_EOF

chmod +x "$SPY_TLT_LAUNCHER" "$RAG_LAUNCHER"
ok "spy-tlt launcher: $SPY_TLT_LAUNCHER"
ok "rag launcher:     $RAG_LAUNCHER"

# Resolve the launcher paths through the SKILLS_DST symlink for the registration
# prompt — that's the path students see in their Skills directory and the path
# supervisord-user.conf will reference.
SPY_TLT_LAUNCHER_PUBLIC="$SKILLS_DST/course-setup/scripts/run-spy-tlt-server.sh"
RAG_LAUNCHER_PUBLIC="$SKILLS_DST/course-setup/scripts/run-rag-server.sh"

# ─────────────────────────────────────────────────────────────────────────────
# 5. Install Ollama if missing
# ─────────────────────────────────────────────────────────────────────────────
step "Checking Ollama"

if command -v ollama >/dev/null 2>&1; then
  skip "ollama already installed ($(ollama --version 2>&1 | head -n1))"
else
  warn "ollama not found — installing from ollama.com"
  # Ollama's installer extracts a zstd-compressed tarball; ensure zstd is available first
  if ! command -v zstd >/dev/null 2>&1; then
    warn "  zstd not found — required by Ollama installer; installing"
    if command -v apt-get >/dev/null 2>&1; then
      sudo apt-get install -y zstd >/dev/null 2>&1 || \
        fail "failed to install zstd. Run 'sudo apt-get install -y zstd' manually and retry."
    else
      fail "zstd is required to install Ollama but cannot be auto-installed on this system. Install zstd and retry."
    fi
    ok "  zstd installed"
  fi
  curl -fsSL https://ollama.com/install.sh | sh || \
    fail "ollama install failed. If your Zo box restricts sudo, ask Zo support to enable Ollama, then re-run this script."
  ok "ollama installed"
fi

# ─────────────────────────────────────────────────────────────────────────────
# 6. Ensure ollama daemon is running
# ─────────────────────────────────────────────────────────────────────────────
step "Starting ollama daemon"

if curl -sf http://127.0.0.1:11434/api/tags >/dev/null 2>&1; then
  skip "ollama daemon already responding on 127.0.0.1:11434"
else
  warn "ollama daemon not responding — starting in background"
  nohup ollama serve >/tmp/ollama.log 2>&1 &
  # Wait up to 30s for the daemon to come up
  for i in {1..30}; do
    if curl -sf http://127.0.0.1:11434/api/tags >/dev/null 2>&1; then
      ok "ollama daemon up (logs: /tmp/ollama.log)"
      break
    fi
    sleep 1
    [[ $i -eq 30 ]] && fail "ollama daemon failed to start within 30s. See /tmp/ollama.log"
  done
fi

# ─────────────────────────────────────────────────────────────────────────────
# 7. Pull gemma4:e2b
# ─────────────────────────────────────────────────────────────────────────────
step "Pulling gemma4:e2b"

if ollama list 2>/dev/null | awk '{print $1}' | grep -qx "gemma4:e2b"; then
  skip "gemma4:e2b already present"
else
  warn "gemma4:e2b not present — pulling (this can take several minutes on a fresh box)"
  ollama pull gemma4:e2b
  ok "gemma4:e2b pulled"
fi

# ─────────────────────────────────────────────────────────────────────────────
# 8. Patch RAG config.json to use gemma4:e2b
# ─────────────────────────────────────────────────────────────────────────────
step "Pointing PageIndex RAG at gemma4:e2b"

RAG_CONFIG="$RAG_DIR/config.json"
[[ -f "$RAG_CONFIG" ]] || fail "Missing $RAG_CONFIG"

python3 - <<PYEOF
import json, sys
from pathlib import Path

cfg_path = Path("$RAG_CONFIG")
cfg = json.loads(cfg_path.read_text())
changed = False
for key in ("ollama_model", "summary_model"):
    if cfg.get(key) != "gemma4:e2b":
        cfg[key] = "gemma4:e2b"
        changed = True
if changed:
    cfg_path.write_text(json.dumps(cfg, indent=2) + "\n")
    print("  patched config.json → ollama_model=summary_model=gemma4:e2b")
else:
    print("  config.json already pinned to gemma4:e2b")
PYEOF
ok "RAG config aligned with gemma4:e2b"

# ─────────────────────────────────────────────────────────────────────────────
# 9. Install consumer skills into /home/workspace/Skills/
# ─────────────────────────────────────────────────────────────────────────────
step "Installing consumer skills into $SKILLS_DST"

mkdir -p "$SKILLS_DST"
for skill in spy-tlt-course pageindex-rag-course course-setup; do
  src="$SKILLS_SRC/$skill"
  dst="$SKILLS_DST/$skill"
  if [[ ! -d "$src" ]]; then
    warn "skipping $skill — not present in repo at $src"
    continue
  fi
  if [[ -d "$dst" ]] && [[ "$(readlink -f "$dst" 2>/dev/null || echo)" == "$(readlink -f "$src")" ]]; then
    skip "$skill already symlinked → repo"
    continue
  fi
  rm -rf "$dst"
  ln -s "$src" "$dst"
  ok "$skill → $dst (symlinked to repo so updates flow through git pull)"
done

# ─────────────────────────────────────────────────────────────────────────────
# 10. Verify
# ─────────────────────────────────────────────────────────────────────────────
step "Running verify.sh"
bash "$(dirname "$0")/verify.sh"

# ─────────────────────────────────────────────────────────────────────────────
# Final instructions
# ─────────────────────────────────────────────────────────────────────────────
cat <<EOF

──────────────────────────────────────────────────────────────────────────────
  Setup complete. Last step is in Zo chat — bootstrap can't register MCP
  servers for you. Paste the block below into Zo chat verbatim.

  IMPORTANT: the Command field MUST be the absolute path to the wrapper
  script. Do NOT add 'cd', '&&', or working-directory arguments —
  supervisord-user execs the command literally and any shell construct
  will silently fail. The wrappers below already cd internally and use
  the absolute uv path.

  ─── Begin paste ───────────────────────────────────────────────────────
  Register two MCP user services for this workspace.

  CRITICAL: For each service below, follow this order exactly. Do NOT
  use update_user_service — it has a known Zo bug where it updates
  Zo's internal database WITHOUT rewriting /etc/zo/supervisord-user.conf,
  which leaves supervisord running the previous (potentially broken)
  entrypoint while the database reports success.

    For EACH of the two services:
      1. Check whether the service is already registered
         (list_user_services or equivalent).
      2. If it exists, call unregister_user_service FIRST. This stops
         the old process and removes the supervisord-user.conf entry.
      3. Call register_user_service with the spec below verbatim.

  Service 1:
    Name:      spy-tlt-course
    Command:   $SPY_TLT_LAUNCHER_PUBLIC
    Transport: stdio MCP

  Service 2:
    Name:      page-index-rag-course
    Command:   $RAG_LAUNCHER_PUBLIC
    Transport: stdio MCP

  After registering, paste the output of these three checks back to me:

    (a) Both services running:
          supervisorctl -c /etc/zo/supervisord-user.conf status

    (b) command= lines are absolute wrapper paths, nothing else:
          grep -A 5 '^\[program:' /etc/zo/supervisord-user.conf | grep '^command='

        Expected:
          command=$SPY_TLT_LAUNCHER_PUBLIC
          command=$RAG_LAUNCHER_PUBLIC

    (c) page-index-rag-course's list_documents returns ≥ 7 filings.

  If (b) shows anything different — bash wrappers, cd/&&/&, .venv/bin
  paths, anything other than the two absolute wrapper paths above — the
  update bug bit. Re-do the unregister + register cycle for that
  service. Do NOT patch the conf file with sed.
  ─── End paste ─────────────────────────────────────────────────────────

  Then start Week 1: zo-professional/week-1/exercise/README.md
──────────────────────────────────────────────────────────────────────────────
EOF
